version: '3.9'

services:
  api:
    build: .
    image: youtube-search
    depends_on:
      - db
    ports:
      - "80:80"
    restart: always

  db:
    container_name: db
    image: postgres:12
    ports:
      - "5405:5405"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}
