"""empty message

Revision ID: 986d898568e0
Revises: 
Create Date: 2022-12-18 15:04:04.632522

"""
from alembic import op
import sqlalchemy as sa

import models

# revision identifiers, used by Alembic.
revision = '986d898568e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('__ts_vector__', models.TSVector(), sa.Computed("(setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(description, '')), 'B'))", persisted=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index('idx_video___ts_vector__', ['__ts_vector__'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index('idx_video___ts_vector__', postgresql_using='gin')

    op.drop_table('videos')
    # ### end Alembic commands ###
